language: c++
cache: ccache

os:
  - osx

compiler:
  - clang

install:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - fetch --no-history v8
  - cd v8
  - gclient sync
  - gn gen out.gn/x64.release/ --args='is_debug=false target_cpu="x64" is_component_build=false v8_static_library=true'
  - ninja -C out.gn/x64.release/ v8_libsampler
  - ninja -C out.gn/x64.release/ icu
  - ninja -C out.gn/x64.release/ v8_libplatform
  - ninja -C out.gn/x64.release/ v8_base
  - ninja -C out.gn/x64.release/ v8_initializers
  - ninja -C out.gn/x64.release/ v8_init
  - ninja -C out.gn/x64.release/ v8_external_snapshot
  - ninja -C out.gn/x64.release/ v8_hello_world
  
script: 
  - cd ..
  - mkdir build
  - mkdir build/libs
  - cp v8/out.gn/x64.release/obj/*.a build/libs || echo " skiped"
  - cp v8/out.gn/x64.release/*.a build/libs || echo " skiped"
  - cp v8/out.gn/x64.release/third_party/icu/*.a build/libs || echo " skiped"
  - cp v8/out.gn/x64.release/icudtl.dat build || echo " skiped"
  - cp v8/out.gn/x64.release/snapshot_blob.bin build/ || echo " skiped"
  - cp v8/out.gn/x64.release/natives_blob.bin build/ || echo " skiped"
  - cp v8/out.gn/x64.release/v8_hello_world build/ || echo " skiped"
  - mkdir build/include  
  - cp -R v8/include build/include

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: v8-build
  skip_cleanup: true
  local_dir: build
  region: us-east-2

#after_success: LD_LIBRARY_PATH=. ./v8pp_test -v --run-tests test/console.js test/file.js