language: c++

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - fetch --no-history v8
  - cd v8
  - gclient sync
  - tools/dev/v8gen.py x64.release
  - echo "is_component_build = false" >> out.gn/x64.release/args.gn 
  - echo "v8_static_library = true" >> out.gn/x64.release/args.gn 
  - ninja -C out.gn/x64.release/ v8_headers
  - ninja -C out.gn/x64.release/ v8_libbase
  - ninja -C out.gn/x64.release/ v8_libsampler
  - ninja -C out.gn/x64.release/ icu
  - ninja -C out.gn/x64.release/ v8_libplatform
  - ninja -C out.gn/x64.release/ v8_base
  - ninja -C out.gn/x64.release/ v8_snapshot

install:
  - ninja -C out.gn/x64.release/ v8_hello_world
  
script: 
  - echo "success"

#after_success: LD_LIBRARY_PATH=. ./v8pp_test -v --run-tests test/console.js test/file.js